#!/usr/bin/env python3
"""
Sweep OpenFOAM's surfaceFeatures includedAngle parameter for a given
case, and classify the resulting feature points by x-coordinate region
to distinguish genuine sharp edges from fillet-tessellation noise.

IMPORTANT SIDE EFFECT: this script overwrites system/surfaceFeaturesDict
in the target case repeatedly during the sweep, ending on whatever the
last tested angle was. After the sweep, you must explicitly set
surfaceFeaturesDict to whichever value is actually chosen -- this
script does not do that for you.

This runs the REAL OpenFOAM surfaceFeatures utility at each angle
(not an independent PyVista approximation), since that is the tool
whose behavior actually matters for the downstream mesh.

Region classification (Ahmed body, L=1.044m):
    - "fillet"     : x < FILLET_X_MAX  (front nose region)
    - "rear_box"   : x > REAR_X_MIN    (sharp rear-face box corners)
    - "middle"     : anything in between -- NOT expected a priori;
                     if points show up here, that is new information,
                     not something to assume away.

Usage:
    python3 sweep_included_angle.py <case_dir> <surfaceFeaturesDict_path> \
        --angles 89 90 91 92 93 95 100 110 120

Example:
    python3 sweep_included_angle.py \
        ~/cfd-portfolio/01-ahmed-body/cases/slant00_re4.18M_symtest \
        ~/cfd-portfolio/01-ahmed-body/cases/slant00_re4.18M_symtest/system/surfaceFeaturesDict \
        --angles 89 90 91 92 93 94 95 100 110 120 130 140
"""

import argparse
import re
import subprocess
import sys
from pathlib import Path

FILLET_X_MAX = 0.15   # points below this x are presumed fillet region,
                       # based on observed fillet point coordinates
                       # clustering at x=0.069-0.10 in prior manual checks
REAR_X_MIN = 0.9       # points above this x are presumed rear-face
                       # box-corner region (body rear is at x=1.044)


DICT_TEMPLATE = """/*--------------------------------*- C++ -*----------------------------------*\\
  =========                 |
  \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\\\    /   O peration     | Website:  https://openfoam.org
    \\\\  /    A nd           | Version:  11
     \\\\/     M anipulation  |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    format      ascii;
    class       dictionary;
    object      surfaceFeaturesDict;
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

surfaces ("ahmedBody.stl");

// GENERATED BY sweep_included_angle.py -- DO NOT COMMIT THIS FILE.
// This value is a sweep test value ({angle}), not a chosen final
// setting. After the sweep, explicitly set this dict to the chosen
// value.
includedAngle   {angle};

subsetFeatures
{{
    nonManifoldEdges    yes;
    openEdges           yes;
}}

// ************************************************************************* //
"""


def parse_emesh_points(emesh_path):
    """Parse the points list out of an OpenFOAM .eMesh ASCII file.

    Handles two observed formats:
      - non-empty: "// points:\n\nN\n(\n(x y z)\n...\n)\n"
      - empty:     "// points:\n\n0()\n"  (count and parens adjacent,
                    no coordinate list at all)
    """
    text = emesh_path.read_text()

    # Count and "(" may be separated by whitespace/newline (non-empty
    # case) or directly adjacent (empty case: "0()").
    m = re.search(r"//\s*points:\s*\n\s*(\d+)\s*\(", text)
    if not m:
        raise RuntimeError(f"Could not find points section in {emesh_path}")

    n_points = int(m.group(1))

    if n_points == 0:
        return []

    start = m.end()

    points = []
    coord_pattern = re.compile(r"\(([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)\)")
    remaining = text[start:]
    for match in coord_pattern.finditer(remaining):
        points.append((float(match.group(1)), float(match.group(2)), float(match.group(3))))
        if len(points) == n_points:
            break

    if len(points) != n_points:
        raise RuntimeError(
            f"Expected {n_points} points, parsed {len(points)} -- "
            f"parser likely mismatched with actual file format in {emesh_path}"
        )

    return points


def classify_points(points):
    fillet = [p for p in points if p[0] < FILLET_X_MAX]
    rear = [p for p in points if p[0] > REAR_X_MIN]
    middle = [p for p in points if FILLET_X_MAX <= p[0] <= REAR_X_MIN]
    return fillet, rear, middle


def run_angle(case_dir, dict_path, angle, stl_name):
    dict_path.write_text(DICT_TEMPLATE.format(angle=angle))

    result = subprocess.run(
        ["surfaceFeatures"],
        cwd=case_dir,
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print(f"  angle={angle}: surfaceFeatures FAILED (exit {result.returncode})")
        print(result.stdout[-2000:])
        print(result.stderr[-2000:])
        return None

    emesh_path = case_dir / "constant" / "triSurface" / f"{stl_name}.eMesh"
    if not emesh_path.exists():
        print(f"  angle={angle}: .eMesh file not found at {emesh_path}")
        return None

    points = parse_emesh_points(emesh_path)
    fillet, rear, middle = classify_points(points)
    return {
        "angle": angle,
        "total": len(points),
        "fillet": len(fillet),
        "rear": len(rear),
        "middle": len(middle),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("case_dir", type=Path)
    parser.add_argument("dict_path", type=Path)
    parser.add_argument("--angles", type=float, nargs="+", required=True)
    parser.add_argument("--stl-name", default="ahmedBody",
                         help="Base name of the STL/eMesh (default: ahmedBody)")
    args = parser.parse_args()

    print(f"{'Angle':>7} | {'Total':>6} | {'Fillet (x<%.2f)' % FILLET_X_MAX:>16} "
          f"| {'Rear (x>%.2f)' % REAR_X_MIN:>14} | {'Middle':>7}")
    print("-" * 65)

    results = []
    for angle in args.angles:
        r = run_angle(args.case_dir, args.dict_path, angle, args.stl_name)
        if r is None:
            continue
        results.append(r)
        print(f"{r['angle']:>7} | {r['total']:>6} | {r['fillet']:>16} "
              f"| {r['rear']:>14} | {r['middle']:>7}")

    print("\nNOTE: surfaceFeaturesDict now contains the LAST tested angle "
          f"({args.angles[-1]}). This is a sweep artifact, not a chosen "
          "value -- set it explicitly before proceeding.")

    clean = [r for r in results if r["fillet"] == 0 and r["rear"] > 0 and r["middle"] == 0]
    if clean:
        print(f"\nAngles achieving fillet=0, rear>0, middle=0 (clean separation): "
              f"{[r['angle'] for r in clean]}")
    else:
        print("\nNo tested angle achieved a clean separation "
              "(fillet=0, rear>0, middle=0). Angle-based filtering alone "
              "may not fully resolve fillet-vs-edge overlap at this "
              "tessellation resolution.")


if __name__ == "__main__":
    main()
